#server:
#  port: 8090
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mall?useSSL=false
#    username: root
#    password: 123456
#
#mybatis:
#
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.st.mall.common.bean
#
## 配置jwt拦截器放行的白名单
#white-list:
#  rules:
#    - regPath: "^/goods.*"
#      method: GET
#    - regPath: "^/category/[\\d]+"
#      method: GET
## /category/{id} GET
## /goods/** GET
#st:
#  picDir: D:/situ/code/Project02/pic/