server:
  port: 8090

spring:
  application:
    name: goods_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456
seata:
  registry:
    type: zk
    zk:
      service-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
  tx-service-group: mall
  service:
    # 事务分组与集群映射的关系
    vgroup-mapping:
      mall: seata
dubbo:
  application:
    name: goods_service
    qos-port: 28090
  protocol:
    name: dubbo
    port: 38090
  registry:
    address: zookeeper://localhost:2181

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean

# 配置jwt拦截器放行的白名单
white-list:
  rules:
    - regPath: "^/goods.*"
      method: GET
    - regPath: "^/category/[\\d]+"
      method: GET
# /category/{id} GET
# /goods/** GET
st:
  picDir: D:/situ/code/Project02/pic/

logging:
  level:
    org.springframework: DEBUG
