# \u5E94\u7528\u7684\u7AEF\u53E3
server:
  port: 8091
# \u8FDE\u63A5\u6C60
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456
# \u914D\u7F6EMyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean
  mapper-locations: classpath:com/st/mall/orderservice/mapper/*.xml
