# 应用服务器端口
server:
  port: 8091
# 配置连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456

dubbo:
  application:
    name: user_service
    qos-port: 28091
  protocol:
    name: dubbo
    port: 38091
  registry:
    address: zookeeper://localhost:2181

redis:
  host: loaclhost
  port: 6379

debug: true

# 配置MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean
  mapper-locations: classpath:com/st/mall/orderservice/mapper/*.xml
