
server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456

dubbo:
  application:
    name: order_service
    qos-port: 28093
  protocol:
    name: dubbo
    port: 38093
  registry:
    address: zookeeper://localhost:2181

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean
