
server:
  port: 8092

spring:
  application:
    name: admin_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
seata:
  registry:
    type: zk
    zk:
      service-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
  tx-service-group: mall
  service:
    # 事务分组与集群映射的关系
    vgroup-mapping:
      mall: seata


main:
  allow-bean-definition-overriding: true

debug: true

mybatis:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean

#white-list:
#  rules:
#    - regPath: ""
#      method: GET
