
server:
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

mybatis:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.st.mall.common.bean
white-list:
  rules:
    - regPath: ""
      method: GET
